### ISSUE TITLE
Question: Is it possible to resize the original images?

### ISSUE THREAD

**Issue by Kikketer** [humhub-contrib/gallery#104]
I'm getting a lot of phone uploads in the gallery and I realize there's already some resizing going on for thumbnails but would it be possible to resize the originals as well?

I realize this is specific and should likely be an option in the settings.  My users don't print nor do they overly care to have the original. So in an attempt to speed loading of individual images, I'd like to be able to resize all of the originals to a smaller size.

Perhaps a setting to say "resize to X" or the like that can happen in the background after upload.

**Comment by luke-** [comment]
You can define global max image dimensions in the file settings:
https://docs.humhub.org/docs/admin/config-options#file

**Comment by Kikketer** [comment]
Perfect thank you. Ignore my "just read the docs" question.
