### ISSUE TITLE
Image src is not correct since 1.4.0

### ISSUE THREAD

**Issue by marc4s** [humhub-contrib/gallery#111]
as you see title and alt are correct:
src is may not correct
<img draggable="false" title="8a5d4c5d7b6c3a925366d4419f2420a3.jpg" alt="8a5d4c5d7b6c3a925366d4419f2420a3.jpg" src="http://xxxx.xxx/index.php?r=file%2Ffile%2Fdownload&amp;guid=fa28082a-8694-4c86-af32-2e194d08d492&amp;hash_sha1=5a1c4809#.jpeg" class="slide-content">

humhub shows since upgrade the gallery to 1.4.0 a red warning symbol instead of the picture.

I downgraded the gallery to 1.3.0 but the red warning is still there.

the gallery (posted media in this space) does not show any content.
If i copy the image path I can access the picture.

**Comment by marc4s** [comment]
even different extensions are translated to jpeg - which is wrong and the file is not accessable
PNG to JPEG](https://ibb.co/x690xgm)

**Comment by marc4s** [comment]
in the overview there is a "Small" link to the picture which shows the red warning by "on click". the "strong" link shows the correct picture.

after some time the thumbnail(preview-image) is created but the entry in overview still shows text only. 
but then both links(the small and the strong) are working 
[Overview](https://ibb.co/3z0hkpS)

**Comment by marc4s** [comment]
[Preview in Gallery](https://ibb.co/NrVDnGN)

**Comment by luke-** [comment]
Cannot reproduce. Please give exact steps to reproduce. Ideally on our demo hosting.

**Comment by marc4s** [comment]
sorry, i haven't had time to update here. finally it was a reverse proxy issue which backend was a http connection.
unfortunately, it was not obvious because firefox no longer  indicates mixed content (that was new to me).
humhub from my point of view should be forced to https by the setting of the baseurl. and on top of that it worked in the meantime without any changes to the two webserver configs.
very strange.
you can close here. sorry for taking your time.

**Comment by luke-** [comment]
thanks for the update
