### ISSUE TITLE
unable to locate message source for category 'cfilesmodule.base'.

### ISSUE THREAD

**Issue by BIZ4Africa** [humhub-contrib/gallery#126]
Hi, I'm using Gallery latest version and could not open the configuration page.

I changed CFilesModule to GalleryModule at [this location](https://github.com/humhub-contrib/gallery/blob/master/views/config/index.php#L17) and then it worked.

Is it a bug or my installation as something missing?

Regards

**Comment by yurabakhtin** [comment]
@BIZ4Africa Sorry, it was a bug, thank you for the report! It will be fixed in next release.

@luke- Fixed in PR https://github.com/humhub-contrib/gallery/pull/127.
