### ISSUE TITLE
gallery bug - Settings gallery

### ISSUE THREAD

**Issue by gigastartup** [humhub-contrib/gallery#14]
If I click Gallery settings I have bug. 

<img width="1434" alt="2017-06-18 20 00 04" src="https://user-images.githubusercontent.com/29522613/27262698-fa668fa4-5464-11e7-8608-1274861d1cdb.png">

**Comment by Felli** [comment]
Can you provide the error stack from the ACP?

**Comment by BastusIII** [comment]
This seems to be no gallery specific problem and I cannot reproduce it.
Does it occur in other spaces, too?
What version of HumHub do you use?

**Comment by gigastartup** [comment]
This error has a "user". If you are an administrator, there will be no error. Please login as User and reproduce it.
<img width="1333" alt="2017-07-02 20 25 00" src="https://user-images.githubusercontent.com/29522613/27772162-203055a2-5f65-11e7-9f11-959efce54e5e.png">

**Comment by gigastartup** [comment]
I use Humhub 1.2 and 1.2.1 too. This bug is in Humhub 1.2.0 + Gallery 1.0.0, Humhub 1.2.0 + Gallery 1.0.1, Humhub 1.2.1 + Gallery 1.0.0, Humhub 1.2.1 + Gallery 1.0.1 too

**Comment by BastusIII** [comment]
@gigastartup 
I still cannot reproduce this, sry. I just get redirected to the "no permission" page, which is the expected behavior. 

OK, you should not see the Settings Button if you have no permission change the settings in the first place, but that is another problem ;). Maybe we should just hide the button.

**Comment by gigastartup** [comment]
I do not know your original idea. :) If the average user does not need to customize his own gallery, then you are right. If it should, then it's not a bug.

**Comment by BastusIII** [comment]
Oh I am sorry. I see the bug now. Somehow I missed that you were talking about the gallery on the profile and not the space.
I get the same error there and of course you should be able to change all the settings you like for your galleries on your own profile. I will have a look.

**Comment by BastusIII** [comment]
Okay, I removed the settings option now, as the setting that could be configured (show gallery snippet) was only relevant for galleries in spaces. 

Please checkout the new version :)

**Comment by gigastartup** [comment]
Well ) Sounds good! Thank you :)
