### ISSUE TITLE
Requested resource not found after updating the gallery module

### ISSUE THREAD

**Issue by arnfinnkristensen** [humhub-contrib/gallery#18]
I updated the gallery module to version 1.0.5 to day. When I try to add a picture to the gallery an error message appears. I try to click and drop files but nothing is working. At the particular space the permission for members on the Gallery write access  module is set to allow.

If I set administrator permission on the user the error message does not appear and everything works fine.

The error message looks like this for user that not have the administrative permissions:

`Forespurt ressurs ble ikke fnnet.

{
    "readyState": 4,
    "responseText": "{\"error\":true,\"message\":\"\"}",
    "responseJSON": {
        "error": true,
        "message": ""
    },
    "status": 404,
    "statusText": "Not Found"
}`

**Comment by Felli** [comment]
When this error happens please check `ACP --> Information --> Logging` for the error stacks.

**Comment by buddh4** [comment]
I'll reopen if this is still an issue.
