### ISSUE TITLE
traslation missing create gallery

### ISSUE THREAD

**Issue by victorpdiez** [humhub-contrib/gallery#20]
On 
humhub-modules-gallery/views/custom-gallery/modal_gallery_edit.php

**Title** and **Description** are cannot be translated.

**Comment by Buliwyfa** [comment]
Change
<?= $form->field($galleryForm->instance, 'title'); ?>
<?= $form->field($galleryForm->instance, 'description')->textArea(); ?>
to
<?= $form->field($galleryForm->instance, 'title')->label( Yii::t('GalleryModule.base', 'Title') ); ?>
<?= $form->field($galleryForm->instance, 'description')->textArea()->label( Yii::t('GalleryModule.base', 'Description') ); ?>


and add trasnlation to translation files

**Comment by Buliwyfa** [comment]
see https://github.com/humhub/humhub-modules-gallery/pull/27
