### ISSUE TITLE
Gallery do not support 'jpeg' format

### ISSUE THREAD

**Issue by arnfinnkristensen** [humhub-contrib/gallery#25]
When I try to upload pictures to the gallery modul from my Iphone 5 (pictures that I have saved on my phone) I get an error messages that the fil format is not supported. The file format is jpeg. The gallery module shuld support that. I hope you can add this soon.

**Comment by Buliwyfa** [comment]
big problem since iPhone x and 8 use "jpeg" as default extension.

Why not use HUMHUB default extensions or have a configuration option to change file extension allowed?

**Comment by victorpdiez** [comment]
+1

**Comment by Buliwyfa** [comment]
please look into this fix
https://github.com/Buliwyfa/humhub-modules-gallery/pull/1

thanks

**Comment by funkycram** [comment]
+1, please make a new release with this fix !

**Comment by staxDB** [comment]
+1

**Comment by macrophone** [comment]
+1
