### ISSUE TITLE
Internal Server Error on large galleries?

### ISSUE THREAD

**Issue by groetzinger** [humhub-contrib/gallery#30]
Hello,
the module works fine. When I create a gallery looks good, too.
Now I have a gallery (in the space) with approx. 210 images (not the smallest one -> 2500px width).

When I open this gallery directly I can see the images. When I go back to the gallery-list (or click in the navigation on "gallery" I get a server error:

An internal server error occurred.Database Exception: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away The SQL being executed was: SELECT `id` FROM `user_http_session` WHERE `id`='xxx'

Is there any problem with big galleries? 

Thanks for your help!

**Comment by buddh4** [comment]
This rather seems to be a problem with your Mysql server https://stackoverflow.com/questions/33250453/how-to-solve-general-error-2006-mysql-server-has-gone-away
