### ISSUE TITLE
(empty) Gallery page inaccessible after install and activation

### ISSUE THREAD

**Issue by cbil** [humhub-contrib/gallery#39]
Hello all,

I had install Humhub on Debian 8 Jessie with php7.4 (fpm), apache2.4.10.
Site running successfull. I install many modules. I use it creating spaces and content. 

When i active Gallery module on one space, if i click on "Gallery" link on left to display Gallery, then i have an error (for link .../gallery/list). 

`yii\base\ErrorException: Trying to access array offset on value of type null in ((path))/protected/modules/gallery/models/StreamGallery.php:49
Stack trace:
#0 ((path))/protected/modules/gallery/models/StreamGallery.php(49): yii\base\ErrorHandler->handleError()
#1 ((path))/protected/modules/gallery/models/BaseGallery.php(118): humhub\modules\gallery\models\StreamGallery->getPreviewImageUrl()
#2 ((path))/protected/modules/gallery/models/StreamGallery.php(82): humhub\modules\gallery\models\BaseGallery->getMetaData()
#3 ((path))/protected/modules/gallery/widgets/GalleryListEntry.php(41): humhub\modules\gallery\models\StreamGallery->getMetaData()
#4 ((path))/protected/vendor/yiisoft/yii2/base/Widget.php(140): humhub\modules\gallery\widgets\GalleryListEntry->run()
#5 ((path))/protected/modules/gallery/widgets/views/galleryList.php(26): yii\base\Widget::widget()
#6 ((path))/protected/vendor/yiisoft/yii2/base/View.php(336): require('((path))/pr...')
#7 ((path))/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile()
#8 ((path))/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#9 ((path))/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render()
#10 ((path))/protected/modules/gallery/widgets/GalleryList.php(30): yii\base\Widget->render()
#11 ((path))/protected/vendor/yiisoft/yii2/base/Widget.php(140): humhub\modules\gallery\widgets\GalleryList->run()
#12 ((path))/protected/modules/gallery/views/list/gallery_list.php(63): yii\base\Widget::widget()
#13 ((path))/protected/vendor/yiisoft/yii2/base/View.php(336): require('((path))/pr...')
#14 ((path))/protected/vendor/yiisoft/yii2/base/View.php(254): yii\base\View->renderPhpFile()
#15 ((path))/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile()
#16 ((path))/protected/vendor/yiisoft/yii2/base/Controller.php(384): yii\base\View->render()
#17 ((path))/protected/modules/gallery/controllers/ListController.php(83): yii\base\Controller->render()
#18 ((path))/protected/modules/gallery/controllers/ListController.php(36): humhub\modules\gallery\controllers\ListController->renderGallery()
#19 [internal function]: humhub\modules\gallery\controllers\ListController->actionIndex()
#20 ((path))/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array()
#21 ((path))/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams()
#22 ((path))/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction()
#23 ((path))/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction()
#24 ((path))/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest()
#25 ((path))/index.php(25): yii\base\Application->run()
#26 {main}`

I edit php code to add a check value of fileArray, and no problem.

` public function getPreviewImageUrl()
    {
        // search for file by given thumbnail id
        $path = $this->getPreviewImageUrlFromThumbFileId();
        if ($path !== null) {
            return $path;
        }
        // get first image from the complete filelist as fallback
        $fileArray = $this->fileListQuery()
                ->orderBy(['content.updated_at' => SORT_DESC])
                ->asArray()
                ->one();
        $file = null;
        if ($fileArray !== null)
                $file = File::findOne($fileArray['id']);
        if ($file !== null && !empty(SquarePreviewImage::getSquarePreviewImageUrlFromFile($file))) {
            return SquarePreviewImage::getSquarePreviewImageUrlFromFile($file);
        }
        // return default image if gallery is empty
        return $this->getDefaultPreviewImageUrl();
    }
`

But why i am alone to have this error ? 

I checking permissions folders, cron execution,etc. all is okay ;)

Thank you,

Regards,
Cédric.

**Comment by buddh4** [comment]
Could not recreate this issue, but I've added an additional check
