### ISSUE TITLE
Automatic downsizing

### ISSUE THREAD

**Issue by Semir1212** [humhub-contrib/gallery#41]
It might be useful to automatically reduce the uploaded images to an acceptable size. The Files module could be used to upload the images in their original size if need be.

**Comment by paul-p** [comment]
+1

**Comment by eptefal** [comment]
+1
today a user uploaded 2 5800x7200 pixel image and the server runs out from resources :(

**Comment by luke-** [comment]
https://docs.humhub.org/docs/admin/uploads#image-compression--downscaling
