### ISSUE TITLE
gallery 1.0.17 gives errors on 1.5.0-beta.1

### ISSUE THREAD

**Issue by logtie** [humhub-contrib/gallery#48]
After update to 1.5.0-beta.1. my humhub only showed my logo and a dot.
after deactive the gallery everythin works fine again.

reinstalled the gallery everything works; but after that i post the first picture humhub was down again

**Comment by luke-** [comment]
Are there any errors in the log?
Administration -> Information -> Logging

**Comment by logtie** [comment]
tried again today to generate the error again. But it seems to be going well until now. I will upload some pictures this week. When it give the error again I will post it here.

**Comment by luke-** [comment]
Ok, thanks!
