### ISSUE TITLE
Since humhub 1.5.1 Galleries in old Space are broken

### ISSUE THREAD

**Issue by wassong** [humhub-contrib/gallery#49]
After Updating to humhub 1.5.1 opening a gallery in old (created before 1.5.1) Space results to a error:
"internal server error"

From logging I got this error message:

yii\base\UnknownPropertyException: Setting unknown property: humhub\modules\gallery\models\SquarePreviewImage::imageInfo in /srv/www/humhub/protected/vendor/yiisoft/yii2/base/BaseObject.php:163 Stack trace: #0 /srv/www/humhub/protected/modules/gallery/models/SquarePreviewImage.php(63): yii\base\BaseObject->__set('imageInfo', Array) #1 /srv/www/humhub/protected/humhub/modules/file/converter/BaseConverter.php(67): humhub\modules\gallery\models\SquarePreviewImage->convert('v93dd751f') #2 /srv/www/humhub/protected/humhub/modules/file/converter/BaseConverter.php(78): humhub\modules\file\converter\BaseConverter->getFilename() #3 /srv/www/humhub/protected/modules/gallery/models/SquarePreviewImage.php(79): humhub\modules\file\converter\BaseConverter->getUrl() #4 /srv/www/humhub/protected/modules/gallery/models/StreamGallery.php(51): humhub\modules\gallery\models\SquarePreviewImage::getSquarePreviewImageUrlFromFile(Object(humhub\modules\file\models\File)) #5 /srv/www/humhub/protected/modules/gallery/models/BaseGallery.php(117): humhub\modules\gallery\models\StreamGallery->getPreviewImageUrl() #6 /srv/www/humhub/protected/modules/gallery/models/StreamGallery.php(83): humhub\modules\gallery\models\BaseGallery->getMetaData() #7 /srv/www/humhub/protected/modules/gallery/widgets/GalleryListEntry.php(42): humhub\modules\gallery\models\StreamGallery->getMetaData() #8 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(140): humhub\modules\gallery\widgets\GalleryListEntry->run() #9 /srv/www/humhub/protected/modules/gallery/widgets/views/galleryList.php(26): yii\base\Widget::widget(Array) #10 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/srv/www/humhub...') #11 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/srv/www/humhub...', Array) #12 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/srv/www/humhub...', Array, Object(humhub\modules\gallery\widgets\GalleryList)) #13 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(236): yii\base\View->render('galleryList', Array, Object(humhub\modules\gallery\widgets\GalleryList)) #14 /srv/www/humhub/protected/modules/gallery/widgets/GalleryList.php(30): yii\base\Widget->render('galleryList', Array) #15 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/Widget.php(140): humhub\modules\gallery\widgets\GalleryList->run() #16 /srv/www/humhub/protected/modules/gallery/views/list/gallery_list.php(63): yii\base\Widget::widget(Array) #17 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(348): require('/srv/www/humhub...') #18 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(257): yii\base\View->renderPhpFile('/srv/www/humhub...', Array) #19 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/View.php(156): yii\base\View->renderFile('/srv/www/humhub...', Array, Object(humhub\modules\gallery\controllers\ListController)) #20 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(386): yii\base\View->render('/list/gallery_l...', Array, Object(humhub\modules\gallery\controllers\ListController)) #21 /srv/www/humhub/protected/modules/gallery/controllers/ListController.php(83): yii\base\Controller->render('/list/gallery_l...', Array) #22 /srv/www/humhub/protected/modules/gallery/controllers/ListController.php(36): humhub\modules\gallery\controllers\ListController->renderGallery() #23 [internal function]: humhub\modules\gallery\controllers\ListController->actionIndex() #24 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array) #25 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\InlineAction->runWithParams(Array) #26 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array) #27 /srv/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('gallery/list', Array) #28 /srv/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #29 /srv/www/humhub/index.php(25): yii\base\Application->run() #30 {main}

Opening a gallery in a new (created with 1.5.1) space doesn't result to an error.

**Comment by luke-** [comment]
Should be fixed with gallery module 1.0.18
