### ISSUE TITLE
DB-Error with max_user_connections

### ISSUE THREAD

**Issue by klauswagner** [humhub-contrib/gallery#50]
I use
- HumHub Version 1.5.1
- VirtualManagedServer with MySQL 5.6.19 and PHP 7.2

Procedure:
- Gallery module installed and activated (in an existing system with a lot of content)
- Module activated in a space with many contents
- Clicked on the "Gallery" menu item in the space navigation
=> System no longer responds.

After some time, "_An internal server error occurred_" appears in the frontend.

If I start e.g. "`yii integrity/run`" via CLI, I get the following error message:
`Exception 'yii\db\Exception' with message 'SQLSTATE[HY000] [1203] User db23***** already has more than 'max_user_connections' active connections'.
`
And in php error.log:
`PDOException: SQLSTATE[HY000] [1203] User db236519_118 already has more than 'max_user_connections' active connections in /kunden/23*****/humhub/protected/vendor/yiisoft/yii2/db/Connection.php:703`

max_user_connections is set to 150 (and unfortunately cannot be increased).

I think the module generates a lot of DB-queries without a limitation of the user_connections because of the already existing content.

**Comment by buddh4** [comment]
Does this problem still occure in the latest module version?

**Comment by klauswagner** [comment]
In my new test with HumHub 1.5.2 and Gallery Version: 1.1.2 it works without Problem.
