### ISSUE TITLE
Add snippet sort_order

### ISSUE THREAD

**Issue by buddh4** [humhub-contrib/gallery#56]

**Comment by MasterMindNET** [comment]
Hello, @buddh4! How would you like to see this feature implemented?

1. Dou you want to have the possibility to move images/galleries with your cursor(drag and drop)?
2. Would you like to have in the settings(icon gear)  have the options like: "A B C", "Z Y X"?

And i you would like to see the first case I beleive it must save this order into DB, right?
Thanks!

**Comment by luke-** [comment]
@MasterMindNET I think it's about the position of the snippet box (widget in the right sidebar).
Probably the best solution here would be to add a simple text field "Sort Order" to the module configuration. The value itself could be stored in the module settings
 
See hardcoded sort order "0"  here:
https://github.com/humhub-contrib/gallery/blob/master/Events.php#L62

**Comment by MasterMindNET** [comment]
> @MasterMindNET I think it's about the position of the snippet box (widget in the right sidebar).
> Probably the best solution here would be to add a simple text field "Sort Order" to the module configuration. The value itself could be stored in the module settings
> 
> See hardcoded sort order "0" here:
> https://github.com/humhub-contrib/gallery/blob/master/Events.php#L62

Good day, @luke-!

That one is fixed now.
Thank you!
