### ISSUE TITLE
No gallery settings available on User profiles

### ISSUE THREAD

**Issue by Vexar180** [humhub-contrib/gallery#58]
In the list of galleries, if a user clicks "Settings", it sends them to a 404 error page.
![exa](https://user-images.githubusercontent.com/28019786/82767530-f4514c00-9ded-11ea-87a1-95eff1280d7a.png)

**Comment by MasterMindNET** [comment]
Good day, @Vexar180!
What version of HubHub and Gallery is running on?

I have HumHub Version: 1.5.2; external-calendar Version: 1.1.2 and it works w/o issues;
Thank you!

**Comment by MasterMindNET** [comment]
It was poorly desired; So, I have found where this error appears.

Here the  steps to reproduce this error:

1. Click on 'User`s Image'(header);
2. 'My profile';
3. Gallery (in the left sidebar);
4. Click on Gear Icon;
5. Press "Settings" option;
6. 404 page (not found) appears.

Expected result: It opens the  settings for the gallery (specify which - in not claer for now).
Actual resultl: 404 page (not found) appears.

![image](https://user-images.githubusercontent.com/22347676/85133775-ff0fcd00-b243-11ea-97fc-109ca7263bfc.png)

**Comment by luke-** [comment]
@MasterMindNET Can you provide a PR for this issue?

**Comment by MasterMindNET** [comment]
> @MasterMindNET Can you provide a PR for this issue?

Where is it supposed to go on this "Settings" click as other gallery settings, right?
Thank you!

**Comment by luke-** [comment]
Hmm ok, I didn't know that.

@buddh4 Do you know if there is a reason why Gallery Snippets are not used on profiles?

**Comment by buddh4** [comment]
The userprofile currently does not have a sidebar.

**Comment by luke-** [comment]
@buddh4 That's one reason, of course. :-) But there's a sidebar in the newer Humhub versions?
![image](https://user-images.githubusercontent.com/4736168/85231566-771ef400-b3f8-11ea-989f-5c03f6f04a4f.png)

**Comment by MasterMindNET** [comment]
Good day!

I have just pushed the last commit to my fork repo:

https://github.com/MasterMindNET/gallery/tree/sortOrderForUserProfile
or
https://github.com/MasterMindNET/gallery/tree/sortOrder
These branches are the same, however, the sortOrder was already merged, so you can merge with my sortOrderForUserProfile, which displays the gallery snippet on the user profile`s page.

Let me know if I can help you in any way!
Thank you!

**Comment by luke-** [comment]
See related PR here:  https://github.com/humhub-contrib/gallery/pull/61

**Comment by MasterMindNET** [comment]
I believe is should closed after merging with [#61](https://github.com/humhub-contrib/gallery/pull/61)
Thank you!

**Comment by luke-** [comment]
Is merged
