### ISSUE TITLE
Undefined index: sort_order

### ISSUE THREAD

**Issue by verement** [humhub-contrib/gallery#67]
After updating to Gallery 1.1.3, when visiting a space gallery, the following error occurs:

```
[error][yii\base\ErrorException:8] yii\base\ErrorException: Undefined index: sort_order in /var/www/humhub/protected/vendor/yiisoft/yii2/data/Sort.php:231
Stack trace:
#0 /var/www/humhub/protected/vendor/yiisoft/yii2/data/Sort.php(231): yii\base\ErrorHandler->handleError(8, 'Undefined index...', '/var/www/humhub...', 231, Array)
#1 /var/www/humhub/protected/vendor/yiisoft/yii2/data/ActiveDataProvider.php(113): yii\data\Sort->getOrders()
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(101): yii\data\ActiveDataProvider->prepareModels()
#3 /var/www/humhub/protected/vendor/yiisoft/yii2/data/BaseDataProvider.php(114): yii\data\BaseDataProvider->prepare()
#4 /var/www/humhub/protected/modules/gallery/controllers/BaseController.php(50): yii\data\BaseDataProvider->getModels()
#5 [internal function]: humhub\modules\gallery\controllers\BaseController->actionIndex()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('', Array)
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('gallery/stream-...', Array)
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request))
#11 /var/www/humhub/index.php(25): yii\base\Application->run()
#12 {main}
```

HumHub version: 1.6.4

**Comment by buddh4** [comment]
Did you try to [clear the cache](https://docs.humhub.org/docs/admin/troubleshooting#clear-cache)? It seems somehow the `sort_order`

**Comment by verement** [comment]
Thanks for the reminder. I have tried it just now but the error still occurs.

**Comment by luke-** [comment]
Hmm, what is the output of "Administration -> Information -> Database"?

**Comment by verement** [comment]
Nothing unusual.

```
        Yii Migration Tool (based on Yii v2.0.38)

No new migrations found. Your system is up-to-date.
```

**Comment by luke-** [comment]
@yurabakhtin Any idea how this could happen?

**Comment by buddh4** [comment]
I think the issue is that we use sort_order as default order which fails in case of the stream gallery, which uses a file record query. And file records do not have a sort_order field. @verement can you approve this only happens if you access the "files from stream" gallery?

**Comment by buddh4** [comment]
ActiveDataProvider creation: https://github.com/humhub-contrib/gallery/blob/master/controllers/BaseController.php#L85
Query of stream gallery: https://github.com/humhub-contrib/gallery/blob/master/models/StreamGallery.php#L90

**Comment by verement** [comment]
> @verement can you approve this only happens if you access the "files from stream" gallery?

Yes, I think that’s right.

Version 1.1.4 no longer has the problem. Thanks!
