### ISSUE TITLE
Rework mobile wall entry

### ISSUE THREAD

**Issue by buddh4** [humhub-contrib/gallery#71]
The mobile wall entry view needs urgend rework:

![grafik](https://user-images.githubusercontent.com/9800854/99088890-ea561c00-25cc-11eb-8471-1612b52548e5.png)

**Comment by yurabakhtin** [comment]
@luke- Fixed in PR https://github.com/humhub-contrib/gallery/pull/92

**Comment by luke-** [comment]
@yurabakhtin Thanks!
