### ISSUE TITLE
Fix Tests

### ISSUE THREAD

**Issue by luke-** [humhub-contrib/gallery#89]

**Comment by yurabakhtin** [comment]
@luke- PR https://github.com/humhub-contrib/gallery/pull/90.
Please note the test errors look strange because locally I couldn't reproduce them, and only after several tryings(you can find 5 commits there) I could get the test checks without errors, but I am not sure they will not appear in future.

**Comment by luke-** [comment]
@yurabakhtin Ok, thanks!

**Comment by luke-** [comment]
Hmm see here: https://github.com/humhub-contrib/gallery/runs/4351949198?check_suite_focus=true

**Comment by yurabakhtin** [comment]
@luke- As I wrote above "I am not sure they will not appear in future", I mean the errors are float i.e. sometimes the tests run  without errors like you can see for the 3 first cases: `PHP 7.4 + develop`, `PHP 7.4 + master`, `PHP 8.0 + develop`, but the last `PHP 8.0 + master` is broken by some unknown reason. Even if you see the errors, it looks like old/cached code is executed:

<img width="1279" alt="test_code" src="https://user-images.githubusercontent.com/6995524/143859489-2a461c83-ea79-4e3e-82e0-96814960d13b.png">

On my local server I cannot reproduce the errors:
<img width="584" alt="gallery_test" src="https://user-images.githubusercontent.com/6995524/143859776-d868e4e7-93b3-4839-8ac4-e870f6c3c8cd.png">

Do you have any idea? Maybe some temp problems on the server where the tests are executed...

**Comment by luke-** [comment]
@yurabakhtin I tried this: https://github.com/humhub-contrib/gallery/commit/03471a2f9b1ffe6b6f308172816c34c6f4b90a3a
Currently the tests are running and I don't see a  impact on the speed/duration with my change.
Let's keep monitoring it.
