### ISSUE TITLE
Image view not reachable for click (Chrome)

### ISSUE THREAD

**Issue by martinbeek** [humhub-contrib/gallery#9]
I can't reach the Show image functionality because "like" and "comment" floating links are in the way. If i want to view an image and click it, it will give a Like... 
![schermafbeelding 2017-06-10 om 18 28 52](https://user-images.githubusercontent.com/6781157/27004560-2bed49ec-4e0b-11e7-9273-4e6472dc0135.png)

**Comment by BastusIII** [comment]
Hi,
The smallest it gets for me in the default theme is:
![grafik](https://user-images.githubusercontent.com/4225867/27643529-a44da278-5c21-11e7-82d6-14e0e6a5745e.png)
What theme and devicewidth do you use?

**Comment by martinbeek** [comment]
I can not click anywhere. All clicks result in a like or unlike. 
This is on a standard browser and on mobile browsers. The space is too small to hold all clickable items. 

![schermafbeelding 2017-06-28 om 21 52 42](https://user-images.githubusercontent.com/6781157/27657235-45b547c2-5c4c-11e7-8c1b-f71cd412589f.png)
![schermafbeelding 2017-06-28 om 21 52 34](https://user-images.githubusercontent.com/6781157/27657236-45ba154a-5c4c-11e7-8065-5403a2addb41.png)

**Comment by martinbeek** [comment]
Standard humhub theme , only background and font colors changed.

**Comment by BastusIII** [comment]
Alright, maybe it is your language, which seems to need one more line of space than in english. I will think of something. Maybe we can replace the text of the like and comment button with icons, so we do not have different spaces used by different languages.

**Comment by BastusIII** [comment]
This happens for devices with a width smaller than about 280px, which is pretty uncommon today :).
Nevertheless, the footer is now hidden when the device with is smaller than 320px, which should solve the problem. 

You can still comment and like the pics via the connected post on the stream.

**Comment by martinbeek** [comment]
> "This happens for devices with a width smaller than about 280px, which is pretty uncommon today"

Uhm... this is happening on all devices - in all browsers. I am on a macbook pro 13 inch. Which is very common today... ;-)

**Comment by BastusIII** [comment]
Sorry for the late response, I had this as fixed in mind.
I don't have a macbook to test. So I emulated different device widths with my browser and could only reproduce your described behavior for widths < 280px. 
Which is strange if you say it happens on all of you devices...
Did anything change for you with the last update?
